(defun fizzbuzz ()
  (do ((i 1 (+ 1 i)))
      ((> i 100))
    (cond ((= (mod i 15) 0)
           (print "FizzBuzz"))
          ((= (mod i 3) 0)
           (print "Fizz"))
          ((= (mod i 5) 0)
           (print "Buzz"))
          (t (print i)))))
